[package]
name = "Starfarer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
ash = { version = "0.37.0+1.3.209", default-features = false, features = ["linked", "debug"]}
ash-window = "0.10.0"
image = "0.24.2"