[package]
name = "starfarer"
version = "0.1.0"
edition = "2021"
authors = ["jtdinsmo <jtdinsmo@mit.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
lepton = { path = "lepton" }
winit = "0.26.1"
ash = { version = "0.37.0+1.3.209", features = ["linked"]}
ash-window = "0.10.0"
image = "0.24.2"
memoffset = "0.6.5"
cgmath = "0.18.0"
num = "0.4.0"
tobj = "3.2.2"
vk-shader-macros = "0.2.8"