[package]
name = "starfarer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.11.2"
sdl2 = { version = "0.34" }
glow_glyph = "0.5.0"
cgmath = "0.18.0"