[package]
name = "starfarer"
version = "0.1.0"
edition = "2021"
authors = ["jtdinsmo <jtdinsmo@mit.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

members = [
    "lepton"
]

[dependencies]
lepton = { path = "lepton" }
cgmath = "0.18.0"