[package]
name = "starfarer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
ash = "0.37.0+1.3.209"
anyhow = "1.0.57"
pretty_env_logger = "0.4.0"